build: rename workflows

diff --git a/.github/workflows/lint-env.yaml b/.github/workflows/lint-env.yaml
--- a/.github/workflows/lint-env.yaml
+++ b/.github/workflows/lint-env.yaml
@@ -1,5 +1,5 @@
 name: Lint
-run-name: Lint PR to ${{ github.head_ref }} by ${{ github.triggering_actor}}
+run-name: Lint PR to ${{ github.base_ref }} by ${{ github.triggering_actor}}
 on:
   pull_request:
     branches: [master, staging]
@@ -9,12 +9,12 @@ jobs:
     runs-on: ubuntu-latest
     steps:
       - name: Check branch
-        if: (github.base_ref == 'staging' && github.head_ref != 'dev') || (github.base_ref == 'master' && github.head_ref != 'staging')
+        if: (github.base_ref == 'master' && github.head_ref != 'staging') || (github.base_ref == 'staging' && github.head_ref != 'dev')
         run: |
-          if [ "${{ github.base_ref }}" == "staging" ]; then
-            echo "ERROR: You can only merge to staging from dev. Current head branch is ${{ github.head_ref }}."
-          elif [ "${{ github.base_ref }}" == "master" ]; then
+          if [ "${{ github.base_ref }}" == "master" ]; then
             echo "ERROR: You can only merge to master from staging. Current head branch is ${{ github.head_ref }}."
+          elif [ "${{ github.base_ref }}" == "staging" ]; then
+            echo "ERROR: You can only merge to staging from dev. Current head branch is ${{ github.head_ref }}."
           fi
           exit 1
 
