build: add branch check to production workflow

diff --git a/.github/workflows/production.yml b/.github/workflows/production.yml
--- a/.github/workflows/production.yml
+++ b/.github/workflows/production.yml
@@ -5,6 +5,15 @@ on:
     branches: [master]
 
 jobs:
+  check-branch:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Check branch
+        if: github.base_ref == 'master' && github.head_ref != 'staging'
+        run: |
+          echo "ERROR: You can only merge to main from dev."
+          exit 1
+
   lint-project:
     runs-on: ubuntu-latest
     steps:
